name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build no_std
      run: cargo build --verbose --no-default-features
    - name: Build with nightly features
      run: cargo build --verbose --features nightly
    - name: Run Clippy
      run: cargo clippy --verbose
    - name: Run Clippy on no_std
      run: cargo clippy --verbose --no-default-features
    - name: Run Clippy with nightly features
      run: cargo clippy --verbose --features nightly
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests on no_std
      run: cargo test --verbose --no-default-features
    - name: Run tests with nightly features
      run: cargo test --verbose --features nightly
